# Generated by Django 3.1.7 on 2021-03-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finish', '0002_remove_pedido_dirección'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Residencia',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
