# Generated by Django 3.1.7 on 2021-03-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finish', '0003_pedido_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Residencia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
